### ISSUE TITLE
Problems with repacking

### ISSUE THREAD

**Issue by kartun83** [ookiineko/magiskboot_build#14]
Hi.
I'm trying to repack boot from this image: 
https://sourceforge.net/projects/evolution-x/files/cupid/14/

specifically : [evolution_cupid-ota-uq1a.231205.015-12181801-OFFICIAL.zip](https://sourceforge.net/projects/evolution-x/files/cupid/14/evolution_cupid-ota-uq1a.231205.015-12181801-OFFICIAL.zip/download)

commandline: ./magiskboot unpack original_boot.img 

output:
```
Parsing boot image: [original_boot.img]
HEADER_VER      [4]
KERNEL_SZ       [37468820]
RAMDISK_SZ      [2086108]
OS_VERSION      [14.0.0]
OS_PATCH_LEVEL  [2023-12]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
RAMDISK_FMT     [lz4_legacy]
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
```

The device is able to boot with this boot.img, so may be there is a problem with the tool ?

**Comment by ookiineko** [comment]
hi there. could you please explain what is the problem you had encountered while unpacking this image? also please use debug builds and tell me your OS version.

also, i have tested unpacking the boot image from the rom zip you linked on my Linux PC, the output is identical to the Magisk's official android build of magiskboot.

**Comment by ookiineko** [comment]
if you mean the issue is that "unexpected ASN.1 DER tag" line, it also happens with official android build of magiskboot binary, i guess just ignore it.
