### ISSUE TITLE
[bug report] extract payload.bin segfaults on windows

### ISSUE THREAD

**Issue by xinleons24** [ookiineko/magiskboot_build#15]
Exract payload.bin no working last cli

**Comment by ookiineko** [comment]
hi. your description of the bug is unclear, please report bugs with more information by using a issue template properly

**Comment by ookiineko** [comment]
you can use your mother tongue if you have difficulties using english, just avoid using slangs and you should be fine.

**Comment by xinleons24** [comment]
The 'Extract payload.bin' is not working properly; when I try to extract any file, such as init_boot or boot, it comes out with a size of 0 KB. I apologize for my English.

**Comment by ookiineko** [comment]
which OS are you on?

**Comment by ookiineko** [comment]
i have tested to extract boot.img from a payload.bin on x86_64 Linux, maybe you can provide a link to the payload.bin you are using, and i can try to reproduce it on my machine

**Comment by xinleons24** [comment]
Windows, I don't think there is an issue with Payload.bin. It extracts successfully with the previous version. There seems to be a problem with the Windows version; I have tried the payload.bin files from at least 6 different models, and the result is consistently a 0 KB extraction.

**Comment by ookiineko** [comment]
okay, thanks for the report, i will test this on my windows pc soon

**Comment by ookiineko** [comment]
i can reproduce the issue, it was a mistake in the windows support code, fixing...

**Comment by ookiineko** [comment]
fixed, please test again with the latest release

**Comment by ookiineko** [comment]
> It extracts successfully with the previous version

that makes sense, this bug was introduced since https://github.com/ookiineko/magiskboot_build/commit/3c4bffb3de9de7a2b7b47fafadeff2a1fb7a35f3
