### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EluneAdore** [ookiineko/magiskboot_build#3]
```shell
~/magiskboot_build$ cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/zys/.bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/zys/.bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test LINUX_IS_USING_GLIBC
-- Performing Test LINUX_IS_USING_GLIBC - Success
CMake Error at CMakeLists.android.txt:3 (add_subdirectory):
  The source directory

    /home/zys/magiskboot_build/vendor/android_fmtlib

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:38 (include)


-- Found Git: /usr/bin/git (found version "2.34.1")
CMake Error at CMakeLists.magisk.txt:12 (message):
  Cannot find Magisk
Call Stack (most recent call first):
  CMakeLists.txt:39 (include)


-- Configuring incomplete, errors occurred!
See also "/home/zys/magiskboot_build/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ookiineko** [comment]
> CMake Error at CMakeLists.android.txt:3 (add_subdirectory):
>   The source directory
> 
>     /home/zys/magiskboot_build/vendor/android_fmtlib
> 
>   does not contain a CMakeLists.txt file.
> CMake Error at CMakeLists.magisk.txt:12 (message):
>   Cannot find Magisk

oops, forgot to mention this project uses Git submodules for dependencies in README

you should clone with `--recurse-submodules`, or do `git submodule update --init --recursive` right now

**Comment by EluneAdore** [comment]
cmake --build build -j $(nproc)
[1/62] Building CXX object CMakeFiles/android_libl...ir/vendor/android_logging/liblog/logger_name.cpp.
/home/zys/magiskboot_build/vendor/android_logging/liblog/logger_name.cpp:25:3: warning: array designators are a C99 extension [-Wc99-designator]
  [LOG_ID_MAIN] = "main",
  ^~~~~~~~~~~~~
1 warning generated.
[22/62] Building CXX object CMakeFiles/android_libbase.dir/vendor/android_libbase/logging.cpp.o
/home/zys/magiskboot_build/vendor/android_libbase/logging.cpp:236:7: warning: array designators are a C99 extension [-Wc99-designator]
      [android::base::VERBOSE] = 7,              // KERN_DEBUG (there is no verbose kernel log
      ^~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[32/62] Building Rust static library libmagiskboot-rs.a
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
[36/62] Building CXX object vendor/android_fmtlib/CMakeFiles/fmt.dir/src/os.cc.o
FAILED: libmagiskboot-rs.a ../vendor/Magisk/native/src/base/base-rs.hpp ../vendor/Magisk/native/src/boot/boot-rs.hpp ../vendor/Magisk/native/src/base/base-rs.cpp ../vendor/Magisk/native/src/boot/boot-rs.cpp /home/zys/magiskboot_build/build/libmagiskboot-rs.a /home/zys/magiskboot_build/vendor/Magisk/native/src/base/base-rs.hpp /home/zys/magiskboot_build/vendor/Magisk/native/src/boot/boot-rs.hpp /home/zys/magiskboot_build/vendor/Magisk/native/src/base/base-rs.cpp /home/zys/magiskboot_build/vendor/Magisk/native/src/boot/boot-rs.cpp
cd /home/zys/magiskboot_build/vendor/Magisk/native/src && /usr/bin/cmake -E env CXXBRIDGE_GEN_TARGET_OS=linux RUSTFLAGS=-Cllvm-args=-opaque-pointers CARGO_TARGET_DIR="/home/zys/magiskboot_build/build/libmagiskboot_target" /home/zys/.cargo/bin/cargo build --target x86_64-unknown-linux-gnu -p magiskboot -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort -r && /usr/bin/cmake -E copy_if_different /home/zys/magiskboot_build/build/libmagiskboot_target/x86_64-unknown-linux-gnu/release/libmagiskboot.a /home/zys/magiskboot_build/build/libmagiskboot-rs.a
[44/62] Building CXX object vendor/android_fmtlib/CMakeFiles/fmt.dir/src/format.cc.o
ninja: build stopped: subcommand failed.

**Comment by ookiineko** [comment]
> [32/62] Building Rust static library libmagiskboot-rs.a
> error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
> See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.

you had installed a non-nightly rust, this is not supported, since upstream uses nightly...

**Comment by EluneAdore** [comment]
zys@DESKTOP-K01QDJF:~/magiskboot_build$ cmake --build build -j $(nproc)
[1/62] Building CXX object CMakeFiles/android_libl...ir/vendor/android_logging/liblog/logger_name.cpp.
/home/zys/magiskboot_build/vendor/android_logging/liblog/logger_name.cpp:25:3: warning: array designators are a C99 extension [-Wc99-designator]
  [LOG_ID_MAIN] = "main",
  ^~~~~~~~~~~~~
1 warning generated.
[22/62] Building CXX object CMakeFiles/android_libbase.dir/vendor/android_libbase/logging.cpp.o
/home/zys/magiskboot_build/vendor/android_libbase/logging.cpp:236:7: warning: array designators are a C99 extension [-Wc99-designator]
      [android::base::VERBOSE] = 7,              // KERN_DEBUG (there is no verbose kernel log
      ^~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[32/62] Building Rust static library libmagiskboot-rs.a
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/zys/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -Cllvm-args=-opaque-pointers --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  rustc -Cllvm-args="..." with: Unknown command line argument '-opaque-pointers'.  Try: 'rustc -Cllvm-args="..." with --help'
  rustc -Cllvm-args="..." with: Did you mean '--frame-pointer'?
[38/62] Building CXX object CMakeFiles/android_libbase.dir/vendor/android_libbase/errors_unix.cpp.o
FAILED: libmagiskboot-rs.a ../vendor/Magisk/native/src/base/base-rs.hpp ../vendor/Magisk/native/src/boot/boot-rs.hpp ../vendor/Magisk/native/src/base/base-rs.cpp ../vendor/Magisk/native/src/boot/boot-rs.cpp /home/zys/magiskboot_build/build/libmagiskboot-rs.a /home/zys/magiskboot_build/vendor/Magisk/native/src/base/base-rs.hpp /home/zys/magiskboot_build/vendor/Magisk/native/src/boot/boot-rs.hpp /home/zys/magiskboot_build/vendor/Magisk/native/src/base/base-rs.cpp /home/zys/magiskboot_build/vendor/Magisk/native/src/boot/boot-rs.cpp
cd /home/zys/magiskboot_build/vendor/Magisk/native/src && /usr/bin/cmake -E env CXXBRIDGE_GEN_TARGET_OS=linux RUSTFLAGS=-Cllvm-args=-opaque-pointers CARGO_TARGET_DIR="/home/zys/magiskboot_build/build/libmagiskboot_target" /home/zys/.cargo/bin/cargo build --target x86_64-unknown-linux-gnu -p magiskboot -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort -r && /usr/bin/cmake -E copy_if_different /home/zys/magiskboot_build/build/libmagiskboot_target/x86_64-unknown-linux-gnu/release/libmagiskboot.a /home/zys/magiskboot_build/build/libmagiskboot-rs.a
[44/62] Building CXX object vendor/android_fmtlib/CMakeFiles/fmt.dir/src/format.cc.o

**Comment by ookiineko** [comment]
please provide full log

**Comment by ookiineko** [comment]
in a file

**Comment by EluneAdore** [comment]
[CMakeError.log](https://github.com/ookiineko/magiskboot_build/files/12776869/CMakeError.log)
[CMakeOutput.log](https://github.com/ookiineko/magiskboot_build/files/12776870/CMakeOutput.log)

**Comment by ookiineko** [comment]
not CMake configure log

```shell
cmake --build build -j1 | tee build.log
```

**Comment by EluneAdore** [comment]
> 请提供完整日志



> 不是 CMake 配置日志
> 
> ```shell
> cmake --build build -j1 | tee build.log
> ```

[build.log](https://github.com/ookiineko/magiskboot_build/files/12776877/build.log)

**Comment by ookiineko** [comment]
my fault, please capture it again using

```shell
cmake --build build -j1 2>&1 | tee build.log
```

**Comment by EluneAdore** [comment]
> 我的错，请使用以下命令再次捕获它
> 
> ```shell
> cmake --build build -j1 2>&1 | tee build.log
> ```

[build.log](https://github.com/ookiineko/magiskboot_build/files/12776886/build.log)

**Comment by ookiineko** [comment]
ok... i will check it later on my linux machine

**Comment by ookiineko** [comment]
fixed in https://github.com/ookiineko/magiskboot_build/commit/38ee271454ddb8bc9b83d7368096a29722b7ccc9

**Comment by EluneAdore** [comment]
> ```shell
> cmake --build build -j1 2>&1 | tee build.log
> ```

[build.log](https://github.com/ookiineko/magiskboot_build/files/12778146/build.log)

**Comment by ookiineko** [comment]
make sure you are able to link simple c++ programs using clang++ and libc++ first

```cpp
#include <iostream>

int main() {
    std::cout << "Hello, world!" << std::endl;

    return 0;
}
```

```shell
clang++ -stdlib=libc++ test.cpp -o test
```

**Comment by ookiineko** [comment]
@ookiineko *with

**Comment by EluneAdore** [comment]
`apt get install libc++abi-15-dev`
Successful
